<?php

define("_HOME", "Home");
define("_ABOUT", "About");
define("_GALLERY", "Gallery");
define("_VIDEO", "Video");
define("_PRODUCT", "Product");
define("_CONTACT", "Contact");
define("_About", "About");
define("_Login","Login");
define("_Service","Service Provided Only In Maharashtra"); 
define("_PROJECTS", "PROJECTS DONE");
define("_HAPPY","HAPPY CLIENTS");
define("_TEAM","TEAM WORKERS");
define("_YEARS","YEARS IN MARKET");
define("_Why"," Why Choose Us");
define("_Phinix"," Phinix Dealers");
define("_Read"," Read More");
define("_Safe","Safe Delivery");
define("_support","support");
define("_Fast","Fast & On Time");
define("_More","More Info");
/*12ton*/
define("_12Ton","12 Ton A4 Brouchure");
define("_RATED","RATED CAPACITY:");
define("_12Tons","12 Tons 36FT and 42FT");
define("_ENGINE","ENGINE");
define("_SimpsonEngine","Simpson Engine BS-III (CEV compliant) - high on power/torque & low on fuel consumption & maintenance");
define("_CABIN","CABIN");
define("_Eergonomically","Eergonomically designed spacious cabin for better front visibility.");
define("_Extraprotection","Extra protection with heavy bar of cabin roof");
define("_HOOKBLOCK","HOOK BLOCK");
define("_SelfAdjusting","Self Adjusting heavy duty hook block with bearing pully.");
define("_WINCH","WINCH");
define("_Heavydutybig","Heavy duty big drum double bearing SAI Winch/Dinamic Winch lor precision handling with 6 fall hook block.");
define("_CYLINDER","CYLINDER WITH O.C. VALVE");
define("_Liftcylinder","Lift cylinder with O.C. valve for protection of hydraulic handling of load.");
define("_SPECIFICATIONS","SPECIFICATIONS");
define("_SimpsonFourCylinder","Simpson, Four Cylinder, Water Cooler Diesel Engine Rated power for crane 49 BHP @ 2200 RPM (max continuous engine rating 58.3 @ 2300 RPM) / Sonalika : 60HP Four Cylinder, Water Cooler Diesel Engine Rated power for crane.");
define("_TRANSMISSION","TRANSMISSION");
define("_Heavydutysliding","Heavy duty, sliding Mesh developed specialIy for crane application. 4 forward and 2 reverse speeds with high & low selector lever.");
define("_Clutch","Clutch");
define("_Heavydutysingle","Heavy duty, single, dry friction, wire woven clutch plate especially designed for crane application.");
define("_TopSpeed","Top Speed");
define("_26KMPHwithoutload","26KMPH without load");
define("_HYDRAULICSYSTEM","HYDRAULIC SYSTEM");
define("_Pump","Pump");
define("_Vanehydraulicpump","Vane hydraulic pump. (Velgon)");
define("_ControlValve","Control Valve");
define("_PrecisionControl","Precision Control & 4 Spool Valve with pressure relief value.");
define("_HydraulicFilter","Hydraulic Filter");
define("_Suctionlinehas","Suction line has a 100 mesh inline strainer while line has 25 micron full flow filter.");
define("_STEERING","STEERING");
define("_Type","Type");
define("_2doubleacting","2 double acting steering with articulated hydraulically Rams.");
define("_Articulation","Articulation");
define("_580articulationthrough","580 articulation through 2 hydraulic cylinders on either side and turning radius of 13Mtrs. (approx) on outer edge of rear wheels.");
define("_TurningRadius","Turning Radius");
define("_Minimum13mtrs","Minimum 13mtrs (approx) on outer edge to rear wheels.");
define("_BRAKES","BRAKES");
define("_FrontWheel","Front Wheel");
define("_Pneumaticallyoperated","Pneumatically operated dual circuit Air brakes.");
define("_RearWheel","Rear Wheel");
define("_Pneumaticallyoperatedatrearwheels","Pneumatically operated at rear wheels.");
define("_Parking","Parking");
define("_ParkingBreakis","Parking Break is pneumaticalIy operated.");
define("_BOOM","BOOM");
define("_Telescoping","Telescoping");
define("_36ft","36ft(10.90 mtr.) 3 Part, 1st & 2nd parts are actuated by hydraulic cylinders.");
define("_Derricking","Derricking");
define("_Opendoubleacting","Open double acting hydraulic cylinders.");
define("_HOISTMECHANISM","HOIST MECHANISM:");
define("_HOIST","HOIST");
define("_4Fallswire","4 Falls wire rope with, small drum double bearing SAI winch/Dinamic winch Rope dia 13mm Steel Core.");
define("_CAPACITIES","CAPACITIES");
define("_AirCleaner","Air Cleaner");
define("_1Ltr","1 .00 Ltr.");
define("_10Ltrs","10.00 Ltrs.");
define("_FuelTank","Fuel Tank");
define("_60Ltrs","60Ltrs");
define("_HydraulicTank","Hydraulic Tank");
define("_140Ltrs","140Ltrs");
define("_Transmission","Transmission");
define("_48Ltrs","48.00 Ltrs");
define("_ELECTRICALSYSTEM","ELECTRICAL SYSTEM");
define("_12VSingleBattery","12V (100 AH)Single Battery Negative Earth.");
define("_TYRES","TYRES");
define("_Front","Front");
define("_10","10.00x20	16PR (4 Nos.)");
define("_Rear","Rear");
define("_13","13.00x24 20 PR (2 Nos.)");
define("_SAFETY","SAFETY");
define("_AudioOverloadIndication","Audio Overload Indication. Hose Failure protection. Audio over hoisting indication. Safety brakes on hoist. O.CVaIve in Lift Cylinder. Cylinder guards.");
define("_STANDARDEQUIPMENT","STANDARD EQUIPMENT");
define("_RopsFullenclosedwithviewcabinwithrotomouldcanopy","Rops Full enclosed with view cabin with rotomould canopy, Cabin Fan, F.M Radio with speaker, Mobile Charger, Front and rear work lights, Reflectors & rear view mirror Tool Box with Tool Kit, Gauges Cluster Neter:- A)Water temperature. B)Engine oil Pressure. C)Amp. Meter. D)RPM Meter cum hour Recorder E)Air Pressure.");
define("_OPTIONALEQUIPMENT","OPTIONAL EQUIPMENT");
define("_FIyJib","FIyJib(1.0 Tones Max. Capacity. Safe load indicator Helper Seat/ Slinger Seat Front Out Riggers with hydraulic cylinder Slotted boom. (Fully hydraulic 10.90mtrs. Height) 4 part standard boom Over hoisting hydraulic cutoff Safe load indicator.");
define("_GrossWeight","Gross Weight");
define("_1500","(11,500 Kg.)");
/*14ton*/
define("_14Tons","14 Tons 36’ 42’ 55’FT");
define("_14Ton","14 Ton Brouchure");
define("_1325","13.00x25 20PR (2 Nos.)");
define("_RopsFull","Rops Full enclosed with view cabin with rotomould canopy, Cabin Fan, Mobile Charger, Front and rear work lights, Reflectors & rear view mirror Tool Box with Tool Kit, Gauges :- A)Water temperature. B)Engine oil Pressure. C)Amp. Meter. D)RPM Meter cum hour Recorder E)Air Pressure.");
define("_FIyJibTonesMax","FIyJib(1.0 Tones Max. Capacity. Safe load indicator Helper Seat/ Slinger Seat Front Out Riggers with hydraulic cylinder Slotted boom. (Fully hydraulic 10.90mtrs. Height)Over hoisting hydraulic cutoff Safe load indicator.");
define("_grossweight","Gross Weight");
define("_12800","(12,800Kg.)");
/*15ton65*/
define("_15Ton","15 Ton 65 Feet");
define("_72ft","72ft (22.0 mtr.) 4 Part, 2nd & 3rd parts are actuated by hydraulic cylinders and 4th part by hydraulicly assisted by rope.");
define("_6Fallswire","6 Falls wire rope with, big drum double bearing SAI winch/Dinamic winch Rope dia 13mm Steel Core.");
define("_65Ltrs","65.00 Ltrs.");
define("_190Ltrs","190.00 Ltrs.");
define("_11","11.00x20 - 16PR (4 Nos.)");
define("_1425","14.00x25 - 20 PR (2 Nos.)");
define("_FlyJib","Fly Jib (1.0 Tones Max. Capacity. Safe load indicator Helper Seat/ Slinger Seat Front Out Riggers with hydraulic cylinder Slotted boom. (Fully hydraulic 16.66mtrs. Height) 4 part standard boom.Over hoisting hydraulic cutoff Safe load indicator.");
define("_13800Kg","(13,800Kg.)");
/*15ton72*/
define("_15Ton72","15 Ton 72 Feet");
define("_Precision","Precision Control & 6 Spool Valve with pressure relief value.");
define("_Saibaba","Saibaba Shopping Center,Shop No.35 Station Road,Kopargaon Tal. Kopargaon Dist.Ahmednagr,423601");
define("_Phone","Phone");
define("_Links","Links");
define("_AdditionalLinks","Additional Links");
define("_CONNECTWITHUS","CONNECT WITH US");
define("_PuneOffice","Pune Office");
define("_7319192008","7319192008",);
define("_9881832002","9881832002");
define("_PunePandharpur","Pune-Pandharpur Road, Garage Line Shop NO.5 Near Ranade Petrol Pump,Phaltan Tal.Phaltan Dist.Satara,415523");
define("_name","Full Name");
define("_Email","Email Id");
define("_Submit","Submit");
define("_All","All Rights Reserved Design & Developed by");
define("_AUTHORISED","AUTHORISED SALES & SERVICE DEALER"); 
define("_for","For Shaktti Construction & Equipment Pvt. Ltd..");
define("_Message","Message");
define("_PostComment","Post Comment");





?>